### ISSUE TITLE
Environment requirements

### ISSUE THREAD

**Issue by jing-yu-lim** [yihaosun1124/OfflineRL-Kit#10]
I can't seem to get environment for the code working despite running 'python setup.py install'. Which python version are you using? Are you using mujoco or mujoco_py? Can we have a full requirements.txt? 

Thank you

**Comment by yihaosun1124** [comment]
Sorry for our late reply! We use Python 3.8. Besides the requirements in setup.py, you additionally need to install mujoco-py depending on the version of MuJoCo engine you have installed and D4RL. We have updated our README for clearer instructions.
