### ISSUE TITLE
Log sharing

### ISSUE THREAD

**Issue by rw422scarlet** [yihaosun1124/OfflineRL-Kit#3]
Hi,

Thanks for contributing this great library!

Would you mind sharing some of the logs for users to get a sense of how large different loss values are supposed to be and compare with our reproduced results? In particular, could you share some log files for MOPO and RAMBO, especially for the Hopper environment? 

Thanks again!

**Comment by yihaosun1124** [comment]
Thank you for your interest in our framework! We are currently testing each algorithm on the benchmark, and we will release the logs and reproduced results soon.

**Comment by rw422scarlet** [comment]
Thank you for your reply. I ran your version of RAMBO before the most recent bug fix, using your previous default setting except I followed the author and set adv_weight to 3e-4. The actor and critic loss both blew up after 700 epochs. The actor loss was -5.5e+07 and the critic loss was 6.28e+11 when I terminated training. I was wondering if you have seen that and how is the RAMBO algorithm now?

**Comment by yihaosun1124** [comment]
> Thank you for your reply. I ran your version of RAMBO before the most recent bug fix, using your previous default setting except I followed the author and set adv_weight to 3e-4. The actor and critic loss both blew up after 700 epochs. The actor loss was -5.5e+07 and the critic loss was 6.28e+11 when I terminated training. I was wondering if you have seen that and how is the RAMBO algorithm now?

Please use the most recent version of RAMBO. We've fixed the bug of the adversarial training in RAMBO and the new version will not occur the abnormal loss.

**Comment by rw422scarlet** [comment]
Hi, thank you for getting back and sorry for the late reply! I will check and get back to you!
