### ISSUE TITLE
MOReL reproduction

### ISSUE THREAD

**Issue by George-Chia** [yihaosun1124/OfflineRL-Kit#4]
Thanks for your elegant code. Do you have a plan for MOReL reproduction?

**Comment by yihaosun1124** [comment]
To be honest, we have attempted to reproduce MOReL before, but we were unable to match the performance reported in the original paper. We will continue to work on it and if we are able to reproduce the official performance, we will definitely release it.

**Comment by George-Chia** [comment]
Salute!
