### ISSUE TITLE
Reproducing COMBO

### ISSUE THREAD

**Issue by kaustubhsridhar** [yihaosun1124/OfflineRL-Kit#8]
Hi,
I noticed that your logs and tables are missing the COMBO results. Were you able to reproduce the results in the paper?

Thank you very much for your helpful codebase,
Kaustubh

**Comment by yihaosun1124** [comment]
Thank you for your interest in our codebase! We are currently testing COMBO on the benchmark, and we will release the logs and reproduced results soon.

**Comment by kaustubhsridhar** [comment]
That sounds great. Please let me know if you need any help. I'd be glad to contribute manpower or even compute (run some hyper params).

**Comment by yihaosun1124** [comment]
We are pleased to inform you that we have added reproduced results of COMBO as well as suggested hyperparameters to our repository!
